// <auto-generated />
using Honeydew.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Honeydew.Migrations
{
    [DbContext(typeof(HoneydewContext))]
    [Migration("20180412023123_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Honeydew.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("BelongsId");

                    b.Property<bool>("Complete");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("BelongsId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("Honeydew.Models.Todolist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Todolists");
                });

            modelBuilder.Entity("Honeydew.Models.Todo", b =>
                {
                    b.HasOne("Honeydew.Models.Todolist", "Belongs")
                        .WithMany()
                        .HasForeignKey("BelongsId");
                });
#pragma warning restore 612, 618
        }
    }
}
